"""
Safety Report Generator — builds a final readable markdown report.
Includes: safety score, verdict, risk details, safer clauses,
negotiation questions, cost analysis, and safety comparison.
"""

from datetime import datetime
import io

from modules.cost_calculator import CostResult
from modules.protection_engine import generate_protection_bundle
from modules.risk_analyzer import RiskAnalysisResult

_SEVERITY_EMOJI = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}
_RISK_RECOMMENDATIONS = {
    "Hidden Fees":               "Request a complete fee schedule in writing before signing.",
    "Processing Charges":        "Confirm the exact net disbursal amount after all deductions.",
    "High Penalty":              "Negotiate a penalty cap; check RBI guidelines on permissible rates.",
    "Contact Access Permission": "Demand removal of any contact-access clause — legitimate lenders don't need it.",
    "Data Sharing":              "Insist on a data-protection clause limiting third-party sharing.",
    "Aggressive Recovery Terms": "Check RBI Fair Practice Code; doorstep visits require proper notice.",
    "Unclear Repayment Terms":   "Demand a fixed EMI schedule with total cost clearly stated.",
}


def generate_safety_report(
    analysis: RiskAnalysisResult,
    cost: "CostResult | None" = None,
    agreement_preview: str = "",
) -> str:
    """Build a polished markdown safety report."""
    now = datetime.now().strftime("%d %b %Y, %I:%M %p")
    lines: list[str] = []

    # ── Header ──
    lines += [
        "# 🛡️ LoanGuard AI — Loan Safety Report",
        "",
        f"> Generated: **{now}**  |  Tool: LoanGuard AI (Hackathon MVP)  |  *Not legal advice*",
        "",
        "---",
        "",
    ]

    # ── Score block ──
    score_emoji = "🟢" if analysis.category == "LOW" else ("🟡" if analysis.category == "MEDIUM" else "🔴")
    lines += [
        "## Loan Safety Score",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Safety Score | **{analysis.score} / 10** |",
        f"| Risk Category | {score_emoji} **{analysis.category} RISK** |",
        f"| Risks Found | {len(analysis.findings)} clause(s) flagged |",
        "",
        "### Summary",
        "",
        analysis.summary,
        "",
        "---",
        "",
    ]

    # ── Risk findings ──
    lines += ["## Detected Risks", ""]
    if analysis.findings:
        for i, f in enumerate(analysis.findings, 1):
            sev_emoji = _SEVERITY_EMOJI.get(f.severity.upper(), "⚪")
            rec = _RISK_RECOMMENDATIONS.get(f.category, "Ask the lender to explain this clause in writing.")
            lines += [
                f"### {i}. {sev_emoji} {f.category} &nbsp;&nbsp;`{f.severity.upper()}`",
                "",
                f"**Why it's risky:** {f.explanation}",
                "",
                f"> **Detected clause:**",
                f"> *{f.snippet}*",
                "",
                f"✅ **Recommended action:** {rec}",
                "",
            ]
    else:
        lines += [
            "✅ No specific risky clauses matched our checks.",
            "Manual review is still recommended before signing.",
            "",
        ]

    lines += ["---", ""]

    # ── Cost breakdown ──
    if cost and (cost.promised_amount > 0 or cost.received_amount > 0 or cost.total_repayment > 0):
        lines += [
            "## 💰 True Cost Breakdown",
            "",
            "| Item | Amount |",
            "|------|--------|",
            f"| Promised loan amount | ₹{cost.promised_amount:,.2f} |",
            f"| Amount actually received | ₹{cost.received_amount:,.2f} |",
            f"| Hidden / upfront charges | ₹{cost.hidden_charges:,.2f} |",
            f"| Total repayment | ₹{cost.total_repayment:,.2f} |",
            f"| Extra repayment (over received) | ₹{cost.extra_repayment:,.2f} |",
            f"| **Effective extra cost** | **{cost.effective_cost_pct}%** |",
            "",
            f"**Plain language:** {cost.risk_message}",
            "",
            "---",
            "",
        ]

    # ── Recommendations ──
    lines += ["## 📋 Overall Recommendation", ""]
    lines.append(_overall_recommendation(analysis, cost))
    lines += ["", "---", ""]

    # ── Agreement preview ──
    if agreement_preview:
        preview = agreement_preview[:600].strip()
        if len(agreement_preview) > 600:
            preview += "\n\n… [truncated]"
        lines += [
            "## 📄 Agreement Preview",
            "",
            f"```",
            preview,
            "```",
            "",
            "---",
            "",
        ]

    # ── Footer ──
    lines += [
        "*This report is generated by **LoanGuard AI** for educational and demonstration purposes only.*",
        "*It is **not** legal or financial advice. Always consult a qualified professional before signing any loan agreement.*",
        "",
        f"*Report ID: LG-{int(datetime.now().timestamp())} · {now}*",
    ]

    return "\n".join(lines)


def generate_pdf_report(analysis: RiskAnalysisResult, cost: "CostResult | None" = None, agreement_preview: str = "") -> bytes:
    """Generate a simple PDF version of the safety report and return bytes.

    Falls back to returning a PDF-like plain text if FPDF is not installed.
    """
    md = generate_safety_report(analysis, cost, agreement_preview)

    try:
        from fpdf import FPDF
    except Exception:
        # Return plain bytes of the markdown as a fallback
        return md.encode("utf-8")

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Split lines and write as simple paragraphs
    for line in md.splitlines():
        # Use multicell to wrap long lines
        pdf.multi_cell(0, 7, line)

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf.read()


def _overall_recommendation(analysis: RiskAnalysisResult, cost: "CostResult | None") -> str:
    parts: list[str] = []

    if analysis.category == "HIGH":
        parts.append(
            "⛔ **Do not sign immediately.** Multiple serious risks were found. "
            "Ask the lender to provide written explanations for every flagged clause "
            "and compare against RBI Fair Practice Code guidelines."
        )
    elif analysis.category == "MEDIUM":
        parts.append(
            "⚠️ **Proceed with caution.** Negotiate or remove unclear clauses before signing. "
            "Get the final EMI schedule and total cost of credit in writing."
        )
    else:
        parts.append(
            "✅ **Lower risk detected.** Always verify the numbers, interest rate, "
            "and foreclosure terms match what was verbally promised."
        )

    if cost and cost.hidden_charges > 0:
        parts.append(
            f"\n\n💸 Upfront deductions of ₹{cost.hidden_charges:,.0f} were identified — "
            "confirm every fee line item on your sanction letter before accepting the loan."
        )

    if cost and cost.effective_cost_pct >= 40:
        parts.append(
            "\n\n📊 The effective cost of this loan is very high. "
            "Explore bank or NBFC alternatives and compare APRs before committing."
        )

    return "".join(parts)